package game;

// Interface for recieving elevator requests.
//  Requests are generated by zombies, when they "press" the elevator's buttons.
//  Students should implement this interface.
public interface ElevatorController {
    // Enums
    public enum Direction {
        None,
        Up,
        Down
    }

    // Students should implement this function to return their name.
    public String getStudentName();

    // Event: Game has started
    public void onGameStarted(Game game);

    // Event: "outside-the-elevator" request, requesting an elevator.
    public void onElevatorRequest(int floorIdx, Direction dir); 

    // Event: "inside-the-elevator" request, requesting to go to a floor.
    public void onFloorRequest(int elevatorIdx, int floorIdx);

    // Event: Called each frame of the simulation (i.e. called continuously)
    public void onUpdate(double deltaTime);

    // Command: Tell an elevator to go to a floor and open its doors, allowing zombies to enter/exit at that floor.
    //  Note that arriving at and leaving a floor will clear internal elevator requests (both internal and external)
    //  Students do not need to override this method, instead it should be called to control the elevator.
    public default boolean gotoFloor(int elevatorIdx, int floorIdx) {
        Elevator elevator = Simulation.get().getElevator(elevatorIdx);
        if (elevator != null) {
            elevator.setTargetFloor(floorIdx);
            Game.get().awardPoints(Game.POINTS_ELEVATOR_COMMAND);
        }
        return true;
    }
}
